apiVersion: shipper.booking.com/v1
kind: Application
metadata:
  name: reviewsapi
  namespace: default
spec:
  revisionHistoryLimit: 10
  template:
    clusterRequirements:
      regions:
      - name: eu-west
      capabilities: []
    chart:
      name: nginx
      version: 0.1.0
      repoUrl: https://chartmuseum.local/charts
    values:
      replicaCount: 10
    strategy:
      steps:
      - name: staging
        capacity:
          incumbent: 100
          contender: 1
        traffic:
          incumbent: 100
          contender: 0
      - name: 50/50
        capacity:
          incumbent: 50
          contender: 50
        traffic:
          incumbent: 50
          contender: 50
      - name: full on
        capacity:
          incumbent: 0
          contender: 100
        traffic:
          incumbent: 0
          contender: 100
